---
# tasks file for deploying apache2

- name: Install Apache2
  apt: name=apache2 update_cache=yes state=latest

# Configuring our Apache2
- name: copy vhost to slave
  template:
    src: "laravel.conf.j2"
    dest: "{{path_vhost}}"

- name: Enables new site
  file:
    src: "/etc/apache2/sites-available/laravel.conf"
    dest: "/etc/apache2/sites-enabled/laravel.conf"
    state: link

- name: Removes "default" site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent

