
- name: Deployment of Laravel app
  become: true
  hosts: ubuntu
  vars_files:
    - vars/main.yml
  roles:
    - setup
    - apache2
    - php
    - composer
    - mysql
    - pgsql
    - push
    
